title: "Awanto Hamsi on Github"
description: "Not as you think, don't be fooled by something you see here!"
baseurl: ""
url: "https://antosoekamti.github.io/"
img: "http://antosoekamti.github.io/awanto.png"
repository: https://antosoekamti/antosoekamti.github.io/
paginate: 5
github_profile: "https://github.com/antosoekamti"
